image: gitlab/dind:latest
services:
  - docker:dind
variables:
  REGISTRY_HOST: registry.panda-chi.io
  TEST_IMAGE: $REGISTRY_HOST/$CI_PROJECT_PATH:$CI_BUILD_REF_NAME
  RELEASE_IMAGE: $REGISTRY_HOST/$CI_PROJECT_PATH:latest
before_script:
  - export DOCKER_API_VERSION=1.22
  - docker info
  - docker-compose --version
buildJob:
  script:
    - docker build --pull --build-arg VCS_REF=`git rev-parse --short HEAD`  -t TEST_IMAGE .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.panda-chi.io
    - docker push $TEST_IMAGE
