#!/bin/bash
set -e

if [ "$COMPILE" != true ]; then
    log WARNING Not compiling Python code
    exit 0
fi

log INFO Compiling all Python code in /opt/odoo
log DEBUG PYTHONOPTIMIZE set to $PYTHONOPTIMIZE
export PYTHONOPTIMIZE=0
python -m compileall -q /opt/odoo
